services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - /Users/dooohn/.ollama:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "ollama list || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 60s

  web:
    build: .
    container_name: fastapi
    volumes:
      - ./app:/app
      - ./chroma_db:/chroma_db
      - ./data:/data
      - ./images:/images
      - ./js:/js
      - ./pages:/pages
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      # healthcheck 기반 의존성 (주석처리): ollama: condition: service_healthy
      - ollama
    networks:
      - app-network
    
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app-network:
    driver: bridge